---
title: "Team Germen Obasi"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

This is our template.

# Team Members

1.  [Berke Pekşen](https://emu-hacettepe-analytics.github.io/emu430-fall2023-bpeksjen/)

2.  [Tuna Merih Germen](https://emu-hacettepe-analytics.github.io/emu430-fall2023-tunagermen/)

3.  [Tuncay Özkardeş](https://www.youtube.com/watch?v=hGMgXsggorg)

4.  [Muharrem Baran Acarlı](https://emu-hacettepe-analytics.github.io/emu430-fall2023-baranacarli/)

5.  [Ayberk Bakılan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-AyberkB98/)

6.  [Mehmet Ali Genç](https://emu-hacettepe-analytics.github.io/emu430-fall2023-maligenc/)

# Project Topic

In this project we did in the Data Analysis course, we will use the data on happiness by year and literacy rate by year, which we received from TUIK. The happiness data according to the years we will use includes happiness rates by age groups between 2003 and 2022. The other data we will use, the literacy rate by years, includes the numbers and rates of "literate, illiterate and unknown" by gender between 2008 and 2022. The reason why we chose this data is that we want to learn the relationship between a person's educational status and their sense of happiness. By analyzing these two data groups, we will try to determine whether there is a correlation between these two situations, and if so, what kind of relationship there is between them. As the general purpose of this project and analysis, we will try to prove that these two data, which are thought to be related to each other and seem to have a definite relationship between them, are independent of each other and there will be no correlation.

# Data Set

<table>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p> </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Literate(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Illiterate(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(18-24)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(18-24)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(18-24)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(18-24)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(25-34)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(25-34)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(25-34)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(25-34)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(35-44)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(35-44)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(35-44)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(35-44)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(45-54)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(45-54)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(45-54)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(45-54)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(55-64)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(55-64)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(55-64)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(55-64)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(65+)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Happy(65+)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Neutral(65+)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Unhappy(65+)(%)</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>      </p>
<p>   </p>
<p>Pop(Total)   </p>
<p>   </p>
<p>   </p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>   </p>
<p>   </p>
<p>   </p>
<p>Year</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>   </p></td>
<td><p> </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2008</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>90.007407</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.9925934</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8730600</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>59.09</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12328944</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.69</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.81</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10070734</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>52.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.8</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7927348</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>51.74</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.54</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.71</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5066402</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>56.93</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.67</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>4893423</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>24.36</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.03</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>71517100</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2009</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.08E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.18E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8773965</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.41</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.45</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.14</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12419892</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.92</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.68</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10181458</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>53.49</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.2</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.31</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8195696</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>51.31</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.96</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>17.73</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5306781</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>51.99</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>29.22</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>18.79</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5083414</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>54.27</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>27.79</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>17.94</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>72561312</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2010</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.27E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7.34E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8778710</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>63.93</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.49</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.58</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12647889</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>64.36</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.32</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.32</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10160840</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.49</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.18</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.34</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8406580</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.93</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>29.23</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.84</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5756267</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.28</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>27.82</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5327736</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>60.03</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>27.06</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.92</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>73722988</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2011</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.41E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5.89E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8751624</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>69.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>25</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12801867</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>62</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10403516</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>60.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8578520</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>59.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6020902</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>62.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5490715</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.8</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>74724269</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2012</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.49E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5.08E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8748310</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>64.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12815605</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>65.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>27.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10795237</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.2</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8738619</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6147100</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>59.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>29</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5682003</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>60.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>75627384</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2013</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.53E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>4.74E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8805113</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>65.09</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.82</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8.08</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12830001</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>60.29</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.89</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8.81</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11134409</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.13</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.76</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.11</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8954555</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>54.49</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.16</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.35</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6315645</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.15</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.88</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.97</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>5891694</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>63.36</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>23.62</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>76667864</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2014</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.54E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>4.56E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8871028</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.2</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8.4</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12789496</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.2</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11428673</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>52.1</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.9</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9112684</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>51.5</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.7</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.8</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6527278</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>54.8</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6192962</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>62.8</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>24.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.6</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>77695904</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2015</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.56E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>4.40E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8948367</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>63.787</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.415</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7.798</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12691399</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.606</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.881</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.513</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11755903</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>54.178</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.986</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.835</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9222988</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>51.668</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>34.67</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.662</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6789637</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.07</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.701</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.229</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6495239</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>56.84</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.74</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.42</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>78741053</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2016</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.59E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>4.12E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9015051</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>65.134</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.301</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8.565</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12556452</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.961</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.702</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.338</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12128650</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.228</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.847</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.924</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9504758</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.344</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.746</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.91</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7058684</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>62.3</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>24.942</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.758</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6651503</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>64.476</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>25.031</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.494</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>79814871</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2017</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.62E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>3.85E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9067145</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.3015</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>29.90471</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8.793788</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12528466</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.57135</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.93865</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.49</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12301515</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.8557</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.27907</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.86522</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9730609</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>53.08768</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>32.99353</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.91879</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7337965</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>56.21379</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.01922</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.76699</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>6895385</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>66.0925</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>22.94151</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.96599</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>80810525</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2018</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.64E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>3.58E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9116836</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.35172</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.13875</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.509531</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12609622</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>53.24284</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.39018</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10.36698</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12422098</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>50.74637</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.92331</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.33032</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10012031</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>47.84929</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.42783</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.72288</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7618202</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>55.65419</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.75922</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.58659</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7186204</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>61.1995</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>26.7507</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.04981</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>82003882</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2019</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.67E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>3.26E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9156716</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>56.67982</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.75431</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.565878</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12730328</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>52.04614</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>34.27075</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.68311</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12552227</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>50.64638</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>37.16409</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.18953</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10208932</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>49.70393</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.67746</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.61861</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7944766</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>48.67123</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.50906</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.81971</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7550727</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>58.54024</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>29.23618</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12.22358</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>83154997</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2020</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.70E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>3.05E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9155682</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>47.14917</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>38.632</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.218833</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12689848</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>46.81024</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>38.13035</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.05941</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12708693</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>45.37726</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>39.44927</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.17347</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10148298</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>46.22153</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>38.46309</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.31538</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8151981</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>48.99747</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.50081</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>14.50173</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>7953555</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.74405</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.43805</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>11.8179</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>83614362</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2021</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.71E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>2.85E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9233464</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>44.48447</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.10865</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>20.406887</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12818686</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>46.57319</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.35105</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>17.07576</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12933370</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>50.22658</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.48964</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>16.28378</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10416745</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>48.7543</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.92495</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>17.32076</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8319096</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>50.91547</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>33.71747</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.36706</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8245124</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>56.16328</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>30.82194</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.01478</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>84680273</p>
<p>   </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><p>   </p>
<p>2022</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9.73E+01</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>2.69E+00</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>9160752</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>47.90992</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.41563</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.674453</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12868216</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>46.76606</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>36.63361</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>16.60033</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>12972770</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>47.93897</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.71641</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>16.34462</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>10818158</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>47.96122</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>35.7269</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>16.31188</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8483812</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>52.49462</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>31.68412</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>15.82126</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>8451669</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>57.72237</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>28.60509</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>13.67254</p>
<p>   </p></td>
<td><p>   </p></td>
<td><p>   </p>
<p>85279553</p>
<p>      </p></td>
<td><p>  </p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
